# coding: utf-8
import os
from utils import make_svg

words = {
    "A": "A",
    "B": "B",
    "C": "C",
    "D": "D",
    "E": "E",
    "F": "F",
    "G": "G",
    "H": "H",
    "I": "I",
    "J": "J",
    "K": "K",
    "L": "L",
    "M": "M",
    "N": "N",
    "O": "O",
    "P": "P",
    "Q": "Q",
    "R": "R",
    "S": "S",
    "T": "T",
    "U": "U",
    "V": "V",
    "W": "W",
    "X": "X",
    "Y": "Y",
    "Z": "Z",
    "SHIFT": "Shift",
    "CTRL": "Ctrl",
    "ALT": "Alt",
    "ZERO": "0",
    "ONE": "1",
    "TWO": "2",
    "THREE": "3",
    "FOUR": "4",
    "FIVE": "5",
    "SIX": "6",
    "SEVEN": "7",
    "EIGHT": "8",
    "NINE": "9",
    "LEFT_CTRL": "L Ctrl",
    "LEFT_ALT": "L Alt",
    "LEFT_SHIFT": "L Shift",
    "RIGHT_ALT": "R Alt",
    "RIGHT_SHIFT": "R Shift",
    "RIGHT_CTRL": "R Ctrl",
    "OSKEY": "OS Key",
    "ESC": "Esc",
    "TAB": "Tab",
    "RET": "Return",
    "SPACE": "Spacebar",
    "LINE_FEED": "Enter", # Not too sure about this one...
    "BACK_SPACE": "Backspace",
    "DEL": "Del",
    "SEMI_COLON": ";",
    "PERIOD": ".",
    "COMMA": ",",
    "QUOTE": '"',
    "ACCENT_GRAVE": "`",
    "MINUS": "-",
    "SLASH": "/",
    "BACK_SLASH": "\\",
    "EQUAL": "=",
    "LEFT_BRACKETT": "[",
    "RIGHT_BRACKETT": "]",
    "LEFT_ARROW": "Left",
    "DOWN_ARROW": "Down",
    "RIGHT_ARROW": "Right",
    "UP_ARROW": "Up",
    "NUMPAD_1": "Numpad 1",
    "NUMPAD_2": "Numpad 2",
    "NUMPAD_3": "Numpad 3",
    "NUMPAD_4": "Numpad 4",
    "NUMPAD_5": "Numpad 5",
    "NUMPAD_6": "Numpad 6",
    "NUMPAD_7": "Numpad 7",
    "NUMPAD_8": "Numpad 8",
    "NUMPAD_9": "Numpad 9",
    "NUMPAD_PERIOD": "Numpad .",
    "NUMPAD_SLASH": "Numpad /",
    "NUMPAD_ASTERIX": "Numpad *",
    "NUMPAD_MINUS": "Numpad -",
    "NUMPAD_PLUS": "Numpad +",
    "NUMPAD_ENTER": "Numpad Enter",
    "F1": "F1",
    "F2": "F2",
    "F3": "F3",
    "F4": "F4",
    "F5": "F5",
    "F6": "F6",
    "F7": "F7",
    "F8": "F8",
    "F9": "F9",
    "F10": "F10",
    "F11": "F11",
    "F12": "F12",
    "F13": "F13",
    "F14": "F14",
    "F15": "F15",
    "F16": "F16",
    "F17": "F17",
    "F18": "F18",
    "F19": "F19",
    #"Pause", "||", Do something else here
    "INSERT": "Insert",
    "HOME": "Home",
    "PAGE_UP": "PgUp",
    "PAGE_DOWN": "PgDown",
    "END": "End",
    "LEFTMOUSE": "LMB",
    "RIGHTMOUSE": "RMB",
    "MIDDLEMOUSE": "MMB",
    "ACTIONMOUSE": "LMB",
    "SELECTMOUSE": "RMB",
}
#words = {
#    "SHIFT": "Shift"
#}
for key in words.keys():
    svg = make_svg(words[key], 18)

    with open(os.path.join('images', key + '.svg'), 'w', encoding="utf-8") as f:
        f.write(svg)